import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { useMoodJournal, useAddMoodEntry } from '@/hooks/useMoodJournal';
import { useAuth } from '@/contexts/AuthContext';
import { useChildren } from '@/hooks/useChildren';
import { Heart, Plus, Smile, Battery, Brain, FileText, Download, MapPin, Phone } from 'lucide-react';
import { format } from 'date-fns';

const selfCareActivities = [
  'Took a walk',
  'Exercised',
  'Meditated',
  'Read a book',
  'Called a friend',
  'Had tea/coffee break',
  'Watched something enjoyable',
  'Got fresh air',
  'Practiced deep breathing',
  'Took a nap',
];

const respiteCareProviders = [
  { name: 'Indian Red Cross Society', phone: '1860-180-1234', location: 'Multiple Cities', services: 'Home care, respite' },
  { name: 'HelpAge India', phone: '1800-180-1253', location: 'Pan India', services: 'Caregiver support' },
  { name: 'Asha Kiran (Delhi)', phone: '011-2539-0070', location: 'Delhi', services: 'Day care, respite' },
  { name: 'Spastics Society of India', phone: '022-2523-7010', location: 'Mumbai', services: 'Therapy, day care' },
];

const SelfCarePage = () => {
  const { user } = useAuth();
  const { data: children = [] } = useChildren();
  const { data: moodEntries = [], isLoading } = useMoodJournal();
  const addMoodEntry = useAddMoodEntry();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    entry_date: format(new Date(), 'yyyy-MM-dd'),
    mood_level: 3,
    stress_level: 3,
    energy_level: 3,
    notes: '',
    gratitude: '',
    self_care_done: [] as string[],
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    addMoodEntry.mutate(formData, {
      onSuccess: () => {
        setDialogOpen(false);
        setFormData({
          entry_date: format(new Date(), 'yyyy-MM-dd'),
          mood_level: 3,
          stress_level: 3,
          energy_level: 3,
          notes: '',
          gratitude: '',
          self_care_done: [],
        });
      },
    });
  };

  const generateQuickGuide = () => {
    const child = children[0];
    if (!child) return;
    
    const guide = `
QUICK-START CARE GUIDE
Generated: ${format(new Date(), 'MMMM d, yyyy')}

CHILD INFORMATION
Name: ${child.name}
CP Type: ${child.cp_type || 'Not specified'}
Mobility Level: ${child.mobility_level || 'Not specified'}
Communication: ${child.communication_level || 'Not specified'}

IMPORTANT NOTES:
- Please refer to medication list in app
- Emergency contact: [Add your number]
- Primary doctor: [Add from Care Team]

DAILY ROUTINE:
[Customize based on your child's schedule]

TRIGGERS TO AVOID:
[Add specific triggers]

COMFORT MEASURES:
[Add what helps calm your child]

Generated by Health Hustlers CP Care App
    `.trim();
    
    const blob = new Blob([guide], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `care-guide-${child.name.toLowerCase().replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const moodEmojis = ['😢', '😟', '😐', '🙂', '😊'];
  const stressEmojis = ['😌', '😐', '😰', '😣', '🤯'];
  const energyEmojis = ['😴', '🥱', '😐', '⚡', '🔥'];

  return (
    <div className="container py-8 space-y-6">
      <div>
        <h1 className="font-display text-3xl font-bold">Caregiver Self-Care</h1>
        <p className="text-muted-foreground mt-1">
          You matter too. Take care of yourself to care for others.
        </p>
      </div>

      <Tabs defaultValue="mood" className="space-y-6">
        <TabsList className="grid w-full grid-cols-3 max-w-md">
          <TabsTrigger value="mood">
            <Smile className="h-4 w-4 mr-2" />
            Mood Journal
          </TabsTrigger>
          <TabsTrigger value="respite">
            <Heart className="h-4 w-4 mr-2" />
            Respite Care
          </TabsTrigger>
          <TabsTrigger value="guide">
            <FileText className="h-4 w-4 mr-2" />
            Quick Guide
          </TabsTrigger>
        </TabsList>

        <TabsContent value="mood" className="space-y-6">
          <div className="flex justify-between items-center">
            <p className="text-muted-foreground">Track your well-being. You deserve to be cared for too.</p>
            {user && (
              <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
                <DialogTrigger asChild>
                  <Button variant="hero">
                    <Plus className="h-4 w-4 mr-2" />
                    Daily Check-In
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
                  <DialogHeader>
                    <DialogTitle>How are you feeling?</DialogTitle>
                  </DialogHeader>
                  <form onSubmit={handleSubmit} className="space-y-6">
                    <div className="space-y-3">
                      <Label className="flex items-center gap-2">
                        <Smile className="h-4 w-4" />
                        Mood: {moodEmojis[formData.mood_level - 1]}
                      </Label>
                      <Slider
                        value={[formData.mood_level]}
                        onValueChange={([v]) => setFormData({ ...formData, mood_level: v })}
                        min={1}
                        max={5}
                        step={1}
                      />
                      <div className="flex justify-between text-xs text-muted-foreground">
                        <span>Low</span>
                        <span>High</span>
                      </div>
                    </div>

                    <div className="space-y-3">
                      <Label className="flex items-center gap-2">
                        <Brain className="h-4 w-4" />
                        Stress Level: {stressEmojis[formData.stress_level - 1]}
                      </Label>
                      <Slider
                        value={[formData.stress_level]}
                        onValueChange={([v]) => setFormData({ ...formData, stress_level: v })}
                        min={1}
                        max={5}
                        step={1}
                      />
                    </div>

                    <div className="space-y-3">
                      <Label className="flex items-center gap-2">
                        <Battery className="h-4 w-4" />
                        Energy Level: {energyEmojis[formData.energy_level - 1]}
                      </Label>
                      <Slider
                        value={[formData.energy_level]}
                        onValueChange={([v]) => setFormData({ ...formData, energy_level: v })}
                        min={1}
                        max={5}
                        step={1}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label>Self-care today:</Label>
                      <div className="grid grid-cols-2 gap-2">
                        {selfCareActivities.map((activity) => (
                          <div key={activity} className="flex items-center space-x-2">
                            <Checkbox
                              id={activity}
                              checked={formData.self_care_done.includes(activity)}
                              onCheckedChange={(checked) => {
                                setFormData({
                                  ...formData,
                                  self_care_done: checked
                                    ? [...formData.self_care_done, activity]
                                    : formData.self_care_done.filter((a) => a !== activity),
                                });
                              }}
                            />
                            <Label htmlFor={activity} className="text-sm">{activity}</Label>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="gratitude">One thing I'm grateful for:</Label>
                      <Textarea
                        id="gratitude"
                        value={formData.gratitude}
                        onChange={(e) => setFormData({ ...formData, gratitude: e.target.value })}
                        placeholder="Even small things count..."
                        rows={2}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="notes">Additional thoughts:</Label>
                      <Textarea
                        id="notes"
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        rows={2}
                      />
                    </div>

                    <Button type="submit" className="w-full" disabled={addMoodEntry.isPending}>
                      {addMoodEntry.isPending ? 'Saving...' : 'Save Check-In'}
                    </Button>
                  </form>
                </DialogContent>
              </Dialog>
            )}
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {moodEntries.slice(0, 9).map((entry) => (
              <Card key={entry.id}>
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-3">
                    <span className="font-medium">{format(new Date(entry.entry_date), 'MMM d')}</span>
                    <div className="flex gap-1 text-lg">
                      {moodEmojis[(entry.mood_level || 3) - 1]}
                      {stressEmojis[(entry.stress_level || 3) - 1]}
                      {energyEmojis[(entry.energy_level || 3) - 1]}
                    </div>
                  </div>
                  {entry.gratitude && (
                    <p className="text-sm text-muted-foreground italic mb-2">
                      "💝 {entry.gratitude}"
                    </p>
                  )}
                  {(entry.self_care_done?.length || 0) > 0 && (
                    <p className="text-xs text-success">
                      ✓ {entry.self_care_done?.length} self-care activities
                    </p>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>

          {moodEntries.length === 0 && !isLoading && (
            <Card className="text-center p-12">
              <span className="text-6xl">💝</span>
              <CardTitle className="mt-4 mb-2">Start Your Wellness Journey</CardTitle>
              <CardDescription>Daily check-ins help you track your well-being over time.</CardDescription>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="respite" className="space-y-6">
          <Card className="border-2 border-primary/20 bg-primary/5">
            <CardContent className="p-6">
              <h3 className="font-display font-bold text-lg mb-2">Respite Care Resources</h3>
              <p className="text-muted-foreground">
                Taking a break is essential. Here are organizations in India that can help.
              </p>
            </CardContent>
          </Card>

          <div className="grid md:grid-cols-2 gap-4">
            {respiteCareProviders.map((provider) => (
              <Card key={provider.name} variant="interactive">
                <CardContent className="p-6">
                  <CardTitle className="text-lg">{provider.name}</CardTitle>
                  <div className="space-y-2 mt-3 text-sm">
                    <p className="flex items-center gap-2 text-muted-foreground">
                      <MapPin className="h-4 w-4" />
                      {provider.location}
                    </p>
                    <a href={`tel:${provider.phone}`} className="flex items-center gap-2 text-primary hover:underline">
                      <Phone className="h-4 w-4" />
                      {provider.phone}
                    </a>
                    <p className="text-muted-foreground">
                      Services: {provider.services}
                    </p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="guide" className="space-y-6">
          <Card className="border-2 border-success/20 bg-success/5">
            <CardContent className="p-6">
              <h3 className="font-display font-bold text-lg mb-2">Quick-Start Guide for Sitters</h3>
              <p className="text-muted-foreground mb-4">
                Generate a one-page summary of your child's needs to give to grandparents, babysitters, or new caregivers.
              </p>
              {children.length > 0 ? (
                <Button onClick={generateQuickGuide} variant="hero">
                  <Download className="h-4 w-4 mr-2" />
                  Download Care Guide
                </Button>
              ) : (
                <p className="text-sm text-muted-foreground">
                  Add a child profile first to generate a care guide.
                </p>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>What's Included in the Guide</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>✅ Child's basic information and CP type</li>
                <li>✅ Mobility and communication levels</li>
                <li>✅ Medication reminders (customize in app)</li>
                <li>✅ Emergency contacts</li>
                <li>✅ Daily routine overview</li>
                <li>✅ Triggers and comfort measures</li>
              </ul>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default SelfCarePage;
